name: base
channels:
  - conda-forge
dependencies:
  - black-jupyter>=22.6
  - flit>=3.7
  - isort
  - jupyter
  - jupyter-book>=0.13
  - jupyter-server-proxy
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab-markup
  - jupyterlab_miami_nights
  - mamba
  - mdformat
  - nb_conda_kernels
  - nbconvert
  - nbqa
  - pip
  - plotly>=5  # needed for jupyter lab to render plots
  - python-lsp-server
  - pyupgrade
  - pip:
    - git+https://github.com/choldgraf/jupyter-http-server
