name: deconv
channels:
  - conda-forge
  - defaults
dependencies:
  - altair>=4.2.2
  - black-jupyter>=23.1.0
  - dask>=2023.3.0
  - docker-py
  - flake8>=6.0.0
  - flit>=3.8.0
  - gcsfs>=2023.5
  - google-auth>=2.18
  - google-cloud-bigquery>=3.10.0
  - google-cloud-storage
  - kubernetes>=1.24.3
  # - ipython-sql  # for duckdb in jupyter
  - ipywidgets<8  # github.com/plotly/plotly.py/issues/3686
  - jupyter  # includes ipykernel, nbformat
  - jupyter-book>=0.15.1
  - matplotlib>=3.7.0
  - pandas>=1.5.3  # 2.0 available
  - pip
  - plotly>=5.14.1
  - pyarrow>=11.0.0
  - pylint>=2.16.3
  - pytest>=7.2.1
  - python=3.11
  - python-duckdb>=0.7.1
  - python-kubernetes
  - scikit-learn
  - scipy
  - seaborn
  - universal_pathlib>=0.0.21
  - pip:
    # - "dagit==1.3.4"
    # - "dagster==1.3.4"
    - dagit
    - dagster
    - dagster-pandas
    - dagster-gcp
    - dagster-gcp-pandas
    - dagster-k8s
    - dagster-docker
    - isort
    - kaleido
    - jupysql
    - psycopg2  # for duckdb in jupyter

# conda search --outdated
