name: deconv
channels:
  - conda-forge
  - defaults
dependencies:
  - altair>=4
  - black-jupyter=22.6.0
  - dask
  - docker-py
  - flake8>=4.0.1
  - flit>=3.4
  - gcsfs
  - google-cloud-bigquery
  - google-cloud-storage
  - jupyter  # includes ipykernel, nbformat
  - matplotlib
  - opentelemetry-api
  - opentelemetry-instrumentation
  - pandas>=1.4
  - pandas-profiling
  - pip
  - plotly>=5.6
  - pyarrow
  - pylint>=2.14.5
  - python>=3.10
  - scikit-learn
  - scipy
  - seaborn
  - pip:
    - cloudpathlib[gs]
    - GEOparse
    - gsea-api
    - isort
    - kaleido
    - rope
