name: r
channels:
  - conda-forge
dependencies:
  - mamba
  - r-devtools=2.4
  # - r-duckdb  # no arm64 build
  - r-formatr=1.14
  - r-irkernel=1.3
  - r-languageserver=0.3
  - r-lintr=3.0
  # - r-pak  # fails. see https://github.com/r-lib/pak/issues/480  # - r-pak  # not installable on mac?
  - r-plotly=4.10
  - r-recommended=4.2
  - r-renv=0.16.0
  # - r-renv>=0.17 ?
  # - r-reticulate ?
  - r-stringi=1.7  # required for r-languageserver
  - r-styler=1.9

# maybe also:
# - plotly
# - formatter? import sorter?
# - linter?
# - language server?

# mamba env create -f conda-env-r.yml
# mamba env update -f conda-env-r.yml
