# to create env:
# mamba env create --file conda-env.yml

# to update env:
# mamba env update --name deconv --file conda-env.yml

name: deconv
channels:
  - conda-forge
  - defaults
dependencies:
  - altair>=4
  - dask
  - docker-py
  - flit>=3.4
  - gcsfs
  - google-cloud-storage
  - ipykernel
  - matplotlib
  - opentelemetry-api
  - opentelemetry-instrumentation
  - pandas>=1.4
  - pandas-gbq>=0.17.4
  - pandas-profiling
  - pip
  - plotly>=5.6
  - pyarrow
  - python>=3.10
  - scikit-learn
  - scipy
  - seaborn
  - pip:
    - black[jupyter]
    - cloudpathlib[gs]
    - GEOparse
    - gsea-api
    - isort
    - kaleido
    - rope
