name: base
channels:
  - conda-forge
dependencies:
  - black-jupyter>=22.6
  - flit>=3.7
  - isort
  - jupyterlab
  - jupyter-book>=0.13
  - jupyterlab_code_formatter
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab-markup
  - jupyterlab_miami_nights
  - mamba
  - nb_conda_kernels
  - nbconvert
  - pip
  - python-lsp-server
  - pip:
    - myst-nb
    - jupyterlab-myst[eval]
    - jupyterlab-neon-theme

#  - pre-commit
#  - nbresuse
#    - jupyterlab-plotly  # should work automatically with plotly>=5
