name: py39
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - mamba
  - pandas>=1.4
  - gcsfs
  - google-cloud-storage
  - pandas-profiling
  - scipy
  - scikit-learn
  - seaborn
  - matplotlib
  - plotly>=4.14
  - docker-py
  - jupyterlab-lsp
  - pip:
    - kaleido
    - GEOparse
    - black[jupyter]
    - isort
    - rope

# to create environment from this file:
# conda env create --file <filename.yml>

# to update the env if you change this file:
# conda env update --name py39 --file <filename.yml>

# - jupyterlab_code_formatter

### from old requirements.txt:
# GEOparse
# kaleido
# plotly>=4.14
# speedtest-cli
# version_information
# pandas-profiling[notebook]
# altair
# dbxfs
# xlrd>=1.0.0
# openpyxl
# biopython
# docker
# pandas-gbq
# jupyterlab_github
# jupyterlab-git
# isort
