[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "helpers"
authors = [{name = "William Grisaitis", email = "wgrisaitis@gmail.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/grisaitis"

[tool.isort]
profile = "black"

[tool.black]
exclude = '(\.virtual_documents|\.ipynb_checkpoints|2\.1\ -\ run\ csx.*|2\ -\ run\ csx.*|.*txt\ files\.ipynb)'
